version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "first-aws-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ul7cd8lvaq80"
s3_prefix = "first-aws-sam-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
